arr = [
    "2023Texas Rangers $ Arizona Diamondbacks ",
    "2023Texas Rangers $ Houston Astros ",
    "2023Arizona Diamondbacks $ Philadelphia Phillies ",
    "2023Texas Rangers $ Baltimore Orioles ",
    "2023Houston Astros $ Minnesota Twins ",
    "2023Philadelphia Phillies $ Atlanta Braves ",
    "2023Arizona Diamondbacks $ Los Angeles Dodgers ",
    "2023Texas Rangers $ Tampa Bay Rays ",
    "2023Arizona Diamondbacks $ Milwaukee Brewers ",
    "2023Minnesota Twins $ Toronto Blue Jays ",
    "2023Philadelphia Phillies $ Miami Marlins ",
    "2022Houston Astros $ Philadelphia Phillies ",
    "2022Houston Astros $ New York Yankees ",
    "2022Philadelphia Phillies $ San Diego Padres ",
    "2022New York Yankees $ Cleveland Guardians ",
    "2022Houston Astros $ Seattle Mariners ",
    "2022Philadelphia Phillies $ Atlanta Braves ",
    "2022San Diego Padres $ Los Angeles Dodgers ",
    "2022Cleveland Guardians $ Tampa Bay Rays ",
    "2022San Diego Padres $ New York Mets ",
    "2022Seattle Mariners $ Toronto Blue Jays ",
    "2022Philadelphia Phillies $ St. Louis Cardinals ",
    "2021Atlanta Braves $ Houston Astros ",
    "2021Houston Astros $ Boston Red Sox ",
    "2021Atlanta Braves $ Los Angeles Dodgers ",
    "2021Houston Astros $ Chicago White Sox ",
    "2021Boston Red Sox $ Tampa Bay Rays ",
    "2021Atlanta Braves $ Milwaukee Brewers ",
    "2021Los Angeles Dodgers $ San Francisco Giants ",
    "2021Boston Red Sox $ New York Yankees ",
    "2021Los Angeles Dodgers $ St. Louis Cardinals ",
    "2020Los Angeles Dodgers $ Tampa Bay Rays ",
    "2020Tampa Bay Rays $ Houston Astros ",
    "2020Los Angeles Dodgers $ Atlanta Braves ",
    "2020Tampa Bay Rays $ New York Yankees ",
    "2020Houston Astros $ Oakland Athletics ",
    "2020Los Angeles Dodgers $ San Diego Padres ",
    "2020Atlanta Braves $ Miami Marlins ",
    "2020Tampa Bay Rays $ Toronto Blue Jays ",
    "2020Los Angeles Dodgers $ Milwaukee Brewers ",
    "2020New York Yankees $ Cleveland Indians ",
    "2020San Diego Padres $ St. Louis Cardinals ",
    "2020Houston Astros $ Minnesota Twins ",
    "2020Miami Marlins $ Chicago Cubs ",
    "2020Oakland Athletics $ Chicago White Sox ",
    "2020Atlanta Braves $ Cincinnati Reds ",
    "2019Washington Nationals $ Houston Astros ",
    "2019Houston Astros $ New York Yankees ",
    "2019Washington Nationals $ St. Louis Cardinals ",
    "2019Houston Astros $ Tampa Bay Rays ",
    "2019New York Yankees $ Minnesota Twins ",
    "2019Washington Nationals $ Los Angeles Dodgers ",
    "2019St. Louis Cardinals $ Atlanta Braves ",
    "2019Tampa Bay Rays $ Oakland Athletics ",
    "2019Washington Nationals $ Milwaukee Brewers ",
    "2018Boston Red Sox $ Los Angeles Dodgers ",
    "2018Boston Red Sox $ Houston Astros ",
    "2018Los Angeles Dodgers $ Milwaukee Brewers ",
    "2018Boston Red Sox $ New York Yankees ",
    "2018Houston Astros $ Cleveland Indians ",
    "2018Milwaukee Brewers $ Colorado Rockies ",
    "2018Los Angeles Dodgers $ Atlanta Braves ",
    "2018New York Yankees $ Oakland Athletics ",
    "2018Colorado Rockies $ Chicago Cubs ",
    "2017Houston Astros $ Los Angeles Dodgers ",
    "2017Houston Astros $ New York Yankees ",
    "2017Los Angeles Dodgers $ Chicago Cubs ",
    "2017New York Yankees $ Cleveland Indians ",
    "2017Houston Astros $ Boston Red Sox ",
    "2017Los Angeles Dodgers $ Arizona Diamondbacks ",
    "2017Chicago Cubs $ Washington Nationals ",
    "2017New York Yankees $ Minnesota Twins ",
    "2017Arizona Diamondbacks $ Colorado Rockies ",
    "2016Chicago Cubs $ Cleveland Indians ",
    "2016Cleveland Indians $ Toronto Blue Jays ",
    "2016Chicago Cubs $ Los Angeles Dodgers ",
    "2016Toronto Blue Jays $ Texas Rangers ",
    "2016Cleveland Indians $ Boston Red Sox ",
    "2016Chicago Cubs $ San Francisco Giants ",
    "2016Los Angeles Dodgers $ Washington Nationals ",
    "2016Toronto Blue Jays $ Baltimore Orioles ",
    "2016San Francisco Giants $ New York Mets ",
    "2015Kansas City Royals $ New York Mets ",
    "2015Kansas City Royals $ Toronto Blue Jays ",
    "2015New York Mets $ Chicago Cubs ",
    "2015Kansas City Royals $ Houston Astros ",
    "2015Toronto Blue Jays $ Texas Rangers ",
    "2015Chicago Cubs $ St. Louis Cardinals ",
    "2015New York Mets $ Los Angeles Dodgers ",
    "2015Houston Astros $ New York Yankees ",
    "2015Chicago Cubs $ Pittsburgh Pirates ",
    "2014San Francisco Giants $ Kansas City Royals ",
    "2014Kansas City Royals $ Baltimore Orioles ",
    "2014San Francisco Giants $ St. Louis Cardinals ",
    "2014Kansas City Royals $ Los Angeles Angels of Anaheim ",
    "2014Baltimore Orioles $ Detroit Tigers ",
    "2014San Francisco Giants $ Washington Nationals ",
    "2014St. Louis Cardinals $ Los Angeles Dodgers ",
    "2014Kansas City Royals $ Oakland Athletics ",
    "2014San Francisco Giants $ Pittsburgh Pirates ",
    "2013Boston Red Sox $ St. Louis Cardinals ",
    "2013Boston Red Sox $ Detroit Tigers ",
    "2013St. Louis Cardinals $ Los Angeles Dodgers ",
    "2013Boston Red Sox $ Tampa Bay Rays ",
    "2013Detroit Tigers $ Oakland Athletics ",
    "2013St. Louis Cardinals $ Pittsburgh Pirates ",
    "2013Los Angeles Dodgers $ Atlanta Braves ",
    "2013Tampa Bay Rays $ Cleveland Indians ",
    "2013Pittsburgh Pirates $ Cincinnati Reds ",
    "2012San Francisco Giants $ Detroit Tigers ",
    "2012Detroit Tigers $ New York Yankees ",
    "2012San Francisco Giants $ St. Louis Cardinals ",
    "2012New York Yankees $ Baltimore Orioles ",
    "2012Detroit Tigers $ Oakland Athletics ",
    "2012St. Louis Cardinals $ Washington Nationals ",
    "2012San Francisco Giants $ Cincinnati Reds ",
    "2012Baltimore Orioles $ Texas Rangers ",
    "2012St. Louis Cardinals $ Atlanta Braves ",
    "2011St. Louis Cardinals $ Texas Rangers ",
    "2011Texas Rangers $ Detroit Tigers ",
    "2011St. Louis Cardinals $ Milwaukee Brewers ",
    "2011Detroit Tigers $ New York Yankees ",
    "2011Texas Rangers $ Tampa Bay Rays ",
    "2011St. Louis Cardinals $ Philadelphia Phillies ",
    "2011Milwaukee Brewers $ Arizona Diamondbacks ",
    "2010San Francisco Giants $ Texas Rangers ",
    "2010Texas Rangers $ New York Yankees ",
    "2010San Francisco Giants $ Philadelphia Phillies ",
    "2010Texas Rangers $ Tampa Bay Rays ",
    "2010New York Yankees $ Minnesota Twins ",
    "2010Philadelphia Phillies $ Cincinnati Reds ",
    "2010San Francisco Giants $ Atlanta Braves ",
    "2009New York Yankees $ Philadelphia Phillies ",
    "2009New York Yankees $ Los Angeles Angels of Anaheim ",
    "2009Philadelphia Phillies $ Los Angeles Dodgers ",
    "2009New York Yankees $ Minnesota Twins ",
    "2009Los Angeles Angels of Anaheim $ Boston Red Sox ",
    "2009Los Angeles Dodgers $ St. Louis Cardinals ",
    "2009Philadelphia Phillies $ Colorado Rockies ",
    "2008Philadelphia Phillies $ Tampa Bay Rays ",
    "2008Tampa Bay Rays $ Boston Red Sox ",
    "2008Philadelphia Phillies $ Los Angeles Dodgers ",
    "2008Boston Red Sox $ Los Angeles Angels of Anaheim ",
    "2008Tampa Bay Rays $ Chicago White Sox ",
    "2008Los Angeles Dodgers $ Chicago Cubs ",
    "2008Philadelphia Phillies $ Milwaukee Brewers ",
    "2007Boston Red Sox $ Colorado Rockies ",
    "2007Boston Red Sox $ Cleveland Indians ",
    "2007Colorado Rockies $ Arizona Diamondbacks ",
    "2007Boston Red Sox $ Los Angeles Angels of Anaheim ",
    "2007Cleveland Indians $ New York Yankees ",
    "2007Arizona Diamondbacks $ Chicago Cubs ",
    "2007Colorado Rockies $ Philadelphia Phillies ",
    "2006St. Louis Cardinals $ Detroit Tigers ",
    "2006Detroit Tigers $ Oakland Athletics ",
    "2006St. Louis Cardinals $ New York Mets ",
    "2006Detroit Tigers $ New York Yankees ",
    "2006Oakland Athletics $ Minnesota Twins ",
    "2006New York Mets $ Los Angeles Dodgers ",
    "2006St. Louis Cardinals $ San Diego Padres ",
    "2005Chicago White Sox $ Houston Astros ",
    "2005Chicago White Sox $ Los Angeles Angels of Anaheim ",
    "2005Houston Astros $ St. Louis Cardinals ",
    "2005Chicago White Sox $ Boston Red Sox ",
    "2005Los Angeles Angels of Anaheim $ New York Yankees ",
    "2005St. Louis Cardinals $ San Diego Padres ",
    "2005Houston Astros $ Atlanta Braves ",
    "2004Boston Red Sox $ St. Louis Cardinals ",
    "2004Boston Red Sox $ New York Yankees ",
    "2004St. Louis Cardinals $ Houston Astros ",
    "2004Boston Red Sox $ Anaheim Angels ",
    "2004New York Yankees $ Minnesota Twins ",
    "2004St. Louis Cardinals $ Los Angeles Dodgers ",
    "2004Houston Astros $ Atlanta Braves ",
    "2003Florida Marlins $ New York Yankees ",
    "2003New York Yankees $ Boston Red Sox ",
    "2003Florida Marlins $ Chicago Cubs ",
    "2003New York Yankees $ Minnesota Twins ",
    "2003Boston Red Sox $ Oakland Athletics ",
    "2003Florida Marlins $ San Francisco Giants ",
    "2003Chicago Cubs $ Atlanta Braves ",
    "2002Anaheim Angels $ San Francisco Giants ",
    "2002Anaheim Angels $ Minnesota Twins ",
    "2002San Francisco Giants $ St. Louis Cardinals ",
    "2002Anaheim Angels $ New York Yankees ",
    "2002Minnesota Twins $ Oakland Athletics ",
    "2002San Francisco Giants $ Atlanta Braves ",
    "2002St. Louis Cardinals $ Arizona Diamondbacks ",
    "2001Arizona Diamondbacks $ New York Yankees ",
    "2001New York Yankees $ Seattle Mariners ",
    "2001Arizona Diamondbacks $ Atlanta Braves ",
    "2001Seattle Mariners $ Cleveland Indians ",
    "2001New York Yankees $ Oakland Athletics ",
    "2001Atlanta Braves $ Houston Astros ",
    "2001Arizona Diamondbacks $ St. Louis Cardinals ",
    "2000New York Yankees $ New York Mets ",
    "2000New York Yankees $ Seattle Mariners ",
    "2000New York Mets $ St. Louis Cardinals ",
    "2000New York Yankees $ Oakland Athletics ",
    "2000Seattle Mariners $ Chicago White Sox ",
    "2000St. Louis Cardinals $ Atlanta Braves ",
    "2000New York Mets $ San Francisco Giants ",
]

teams = [
    "Arizona Diamondbacks",
    "Atlanta Braves",
    "Baltimore Orioles",
    "Boston Red Sox",
    "Chicago Cubs",
    "Chicago White Sox",
    "Cincinnati Reds",
    "Cleveland Guardians",
    "Colorado Rockies",
    "Detroit Tigers",
    "Houston Astros",
    "Kansas City Royals",
    "Los Angeles Angels",
    "Los Angeles Dodgers",
    "Miami Marlins",
    "Milwaukee Brewers",
    "Minnesota Twins",
    "New York Mets",
    "New York Yankees",
    "Oakland Athletics",
    "Philadelphia Phillies",
    "Pittsburgh Pirates",
    "San Diego Padres",
    "Seattle Mariners",
    "San Francisco Giants",
    "St. Louis Cardinals",
    "Tampa Bay Rays",
    "Texas Rangers",
    "Toronto Blue Jays",
    "Washington Nationals",
    "League Average",
]

ans = {}
for i in range(2000, 2024):
    ans[i] = set()

for ele in arr:
    t = ele[4:]
    t1 = t.split(" $ ")[0]
    t2 = t.split(" $ ")[1]

    ans[int(ele[0:4])].add(t1.strip())
    ans[int(ele[0:4])].add(t2.strip())

print(ans)

anss = []
for y in range(2023, 1999, -1):
    for t in teams:
        if t in ans[y]:
            anss.append(1)
        else:
            anss.append(0)

for i in ans.values():
    print(len(i))

# for i in anss:
# print(i)
